---
- name: My Playbook for Variables Lesson
  hosts: all
  become: yes

  tasks:

  - debug:
      var: ansible_distribution
      var: ansible_os_family

  #- debug:
  #    var: ansible_lo.ipv4.address

  - shell: uptime
    register: results

  - debug:
      var: results.stdout
