---
language: python
python:
  - 3.6
script:
  - molecule lint
  - molecule destroy
  - molecule dependency
  - molecule syntax
  - molecule converge
  - travis_wait 20 molecule idempotence
  - molecule side-effect
  - molecule verify
  - molecule destroy
