---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: .imported_roles
    force: false
driver:
  name: vagrant
  provider:
    name: parallels
lint:
  name: yamllint
  options:
    config-file: molecule/resources/yamllint.conf
    s: false
platforms:
  - name: common
    box: parallels/ubuntu-16.04
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    provision: false
  - name: zabbix-server
    groups:
      - zabbix_server
    box: parallels/ubuntu-16.04
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    provision: false
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../resources/group_vars/
  env:
    ANSIBLE_ROLES_PATH: ../../roles/:../../.imported_roles/
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
    options:
      exclude:
        - .imported_roles/
scenario:
  name: parallels
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
